title: Mohammed Ameen
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > Exp: 7 years
 Full Stack Engineer
  <br><br>
  <a href="mailto:mohammedameen028@gmail.com">mohammedameen028@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/mohammed-ameen-551583bb/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/mohammedameen028/">Gihub</a> 
theme: jekyll-theme-architect
